[phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "libdrm",
  "mesa",
  "libxkbcommon",
  "libX11",
  "libXcomposite",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXrandr",
  "libgbm",
  "pango",
  "cairo",
  "alsa-lib",
  "expat",
  "libxcb",
  "dbus",
  "udev"
]

[phases.install]
cmds = ["npm install", "npx playwright install-deps", "npx playwright install chromium"]
